import type { Question } from './types';

export const questions: Question[] = [
  // 🧠 Class 1: Evolution of Web (Web1, Web2, Web3)
  {
    id: 1,
    class: 'Class 1',
    question: 'What is the main feature of Web 1.0?',
    options: ['Read/write interaction', 'Read-only era', 'Full data ownership'],
    answer: 'Read-only era',
    type: 'multiple-choice',
  },
  {
    id: 2,
    class: 'Class 1',
    question: 'Web 2.0 allows users to:',
    options: ['Own blockchain assets', 'Only read content', 'Interact with and contribute to content'],
    answer: 'Interact with and contribute to content',
    type: 'multiple-choice',
  },
  {
    id: 3,
    class: 'Class 1',
    question: 'Web 3.0 is known for:',
    options: ['Centralized control', 'Read/write/own experience', 'Only social media features'],
    answer: 'Read/write/own experience',
    type: 'multiple-choice',
  },
  {
    id: 4,
    class: 'Class 1',
    question: 'What is the foundation technology behind Web 3.0?',
    options: ['Blockchain', 'Cloud Computing', 'Data warehousing'],
    answer: 'Blockchain',
    type: 'multiple-choice',
  },
  {
    id: 5,
    class: 'Class 1',
    question: 'True or False: Web 3.0 ensures you own your own data.',
    options: ['True', 'False'],
    answer: 'True',
    type: 'true-false',
  },

  // 🔐 Class 2: Blockchain vs Decentralized Web
  {
    id: 6,
    class: 'Class 2',
    question: 'Blockchain is best described as:',
    options: ['A centralized logbook', 'A decentralized ledger', 'A cryptocurrency'],
    answer: 'A decentralized ledger',
    type: 'multiple-choice',
  },
  {
    id: 7,
    class: 'Class 2',
    question: 'Public and private chains refer to:',
    options: ['Different types of blockchains', 'Social media platforms', 'Government databases'],
    answer: 'Different types of blockchains',
    type: 'multiple-choice',
  },
  {
    id: 8,
    class: 'Class 2',
    question: 'What powers the decentralized web?',
    options: ['Smart contracts', 'Blockchain', 'Traditional servers'],
    answer: 'Blockchain',
    type: 'multiple-choice',
  },
  {
    id: 9,
    class: 'Class 2',
    question: 'What platform helps bridge different blockchains?',
    options: ['MetaMask', 'Uniswap', 'Facebook'],
    answer: 'Uniswap',
    type: 'multiple-choice',
  },
  {
    id: 10,
    class: 'Class 2',
    question: 'True or False: In decentralized systems, there is one central authority.',
    options: ['True', 'False'],
    answer: 'False',
    type: 'true-false',
  },

  // 💸 Class 3: Major Sectors of Web3 – DeFi Explained
  {
    id: 11,
    class: 'Class 3',
    question: 'What was the reason DeFi was created?',
    options: ['To strengthen traditional banks', 'To overcome traditional finance limitations', 'For gaming'],
    answer: 'To overcome traditional finance limitations',
    type: 'multiple-choice',
  },
  {
    id: 12,
    class: 'Class 3',
    question: 'Ethereum is critical in DeFi because it:',
    options: ['Has centralized tokens', "Doesn't support smart contracts", 'Hosts many DeFi protocols'],
    answer: 'Hosts many DeFi protocols',
    type: 'multiple-choice',
  },
  {
    id: 13,
    class: 'Class 3',
    question: 'What is staking in DeFi?',
    options: ['Trading assets', 'Locking assets to earn rewards', 'Taking loans'],
    answer: 'Locking assets to earn rewards',
    type: 'multiple-choice',
  },
  {
    id: 14,
    class: 'Class 3',
    question: 'True or False: You need paperwork to borrow in DeFi.',
    options: ['True', 'False'],
    answer: 'False',
    type: 'true-false',
  },
  {
    id: 15,
    class: 'Class 3',
    question: 'DEX stands for:',
    options: ['Digital Exchange', 'Decentralized Exchange', 'Derivative Exchange'],
    answer: 'Decentralized Exchange',
    type: 'multiple-choice',
  },

  // 🌐 Class 4: Decentralized Applications (Dapps)
  {
    id: 16,
    class: 'Class 4',
    question: 'What is a Dapp?',
    options: ['A decentralized application', 'A centralized application', 'A type of cryptocurrency'],
    answer: 'A decentralized application',
    type: 'multiple-choice',
  },
  {
    id: 17,
    class: 'Class 4',
    question: 'Which of the following is an example of a Web 3.0 Dapp?',
    options: ['Lens Protocol', 'Facebook', 'Google Drive'],
    answer: 'Lens Protocol',
    type: 'multiple-choice',
  },
  {
    id: 18,
    class: 'Class 4',
    question: 'What is the primary purpose of a Dapp?',
    options: ['To operate without centralized control', 'To replace all traditional applications', 'To centralize blockchain technology'],
    answer: 'To operate without centralized control',
    type: 'multiple-choice',
  },
  {
    id: 19,
    class: 'Class 4',
    question: 'What is required to interact with a Dapp?',
    options: ['A blockchain wallet', 'A traditional bank account', 'A centralized server'],
    answer: 'A blockchain wallet',
    type: 'multiple-choice',
  },
  {
    id: 20,
    class: 'Class 4',
    question: 'True or False: Dapps are hosted on centralized servers.',
    options: ['True', 'False'],
    answer: 'False',
    type: 'true-false',
  },

  // 💰 Class 5: Cryptocurrency Basics
  {
    id: 21,
    class: 'Class 5',
    question: 'What is the primary purpose of cryptocurrency?',
    options: ['Medium of exchange and store of value', 'To replace all fiat currencies', 'To centralize financial systems'],
    answer: 'Medium of exchange and store of value',
    type: 'multiple-choice',
  },
  {
    id: 22,
    class: 'Class 5',
    question: 'Which of the following is an example of a cryptocurrency?',
    options: ['Bitcoin', 'PayPal', 'Visa'],
    answer: 'Bitcoin',
    type: 'multiple-choice',
  },
  {
    id: 23,
    class: 'Class 5',
    question: 'What ensures the security of blockchain transactions?',
    options: ['Cryptographic hashing', 'Manual verification', 'Centralized servers'],
    answer: 'Cryptographic hashing',
    type: 'multiple-choice',
  },
  {
    id: 24,
    class: 'Class 5',
    question: 'What is the smallest unit of Bitcoin called?',
    options: ['Ether', 'Satoshi', 'Token'],
    answer: 'Satoshi',
    type: 'multiple-choice',
  },
  {
    id: 25,
    class: 'Class 5',
    question: 'True or False: Cryptocurrencies are controlled by a central authority.',
    options: ['True', 'False'],
    answer: 'False',
    type: 'true-false',
  },

  // 🏛 Class 6: Decentralized Autonomous Organizations (DAOs)
  {
    id: 26,
    class: 'Class 6',
    question: 'What does DAO stand for?',
    options: ['Decentralized Autonomous Organization', 'Digital Asset Organization', 'Distributed Autonomous Operation'],
    answer: 'Decentralized Autonomous Organization',
    type: 'multiple-choice',
  },
  {
    id: 27,
    class: 'Class 6',
    question: 'What is required to participate in a DAO?',
    options: ['Governance tokens', 'A bank account', 'A centralized account'],
    answer: 'Governance tokens',
    type: 'multiple-choice',
  },
  {
    id: 28,
    class: 'Class 6',
    question: 'What is the primary purpose of a DAO?',
    options: ['To operate without centralized control', 'To replace all traditional organizations', 'To centralize blockchain technology'],
    answer: 'To operate without centralized control',
    type: 'multiple-choice',
  },
  {
    id: 29,
    class: 'Class 6',
    question: 'Which of the following is a key feature of a DAO?',
    options: ['Collective decision-making', 'Centralized governance', 'Manual record-keeping'],
    answer: 'Collective decision-making',
    type: 'multiple-choice',
  },
  {
    id: 30,
    class: 'Class 6',
    question: 'True or False: DAOs are governed by smart contracts.',
    options: ['True', 'False'],
    answer: 'True',
    type: 'true-false',
  },
];